# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(default="First Name", max_length=50)),
                ("lastName", models.CharField(default="Last Name", max_length=50)),
                ("birthDate", models.DateField(blank=True, null=True)),
                (
                    "homeAddress",
                    models.CharField(default="Your home address", max_length=200),
                ),
                (
                    "phoneNumber",
                    models.CharField(default="0766 xxx xxx", max_length=20),
                ),
                (
                    "profileImage",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
