# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='membershipCard',
            field=models.ImageField(default='', upload_to='membership_cards'),
        ),
    ]
