# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191020_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homeAddress',
            field=models.CharField(blank=True, default='Your home address', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default='0766 xxx xxx', max_length=20),
        ),
    ]
