# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, default='0766 xxx xxx', max_length=20),
        ),
    ]
