# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191103_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cardID',
            field=models.ImageField(default='default_card.png', upload_to='profile_images/card_ID'),
        ),
    ]
