# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cardID',
            field=models.ImageField(default='profile_images/card_ID/default_card.png', upload_to='profile_images/card_ID'),
        ),
    ]
