# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191117_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
