# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(default='', max_length=60),
        ),
    ]
