# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
    ]
