# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cardID',
        ),
    ]
