# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
