# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
    ]
