# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200222_1025'),
        ('checkout', '0005_order_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='merchandise',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
