# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20200226_2230'),
    ]

    operations = [
    ]
