# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20200226_2232'),
    ]

    operations = [
    ]
