# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollingRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementsForEnrolling', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GearRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredGear', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notionDiscussed', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='requiredGear',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='notionDiscussed',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='requirementsForEnrolling',
        ),
        migrations.AddField(
            model_name='courses',
            name='totalParticipants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='gearrequirements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
        migrations.AddField(
            model_name='enrollingrequirements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
