# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='enrollingrequirements',
            name='course',
        ),
        migrations.RemoveField(
            model_name='gearrequirements',
            name='course',
        ),
        migrations.RemoveField(
            model_name='notions',
            name='course',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='EnrollingRequirements',
        ),
        migrations.DeleteModel(
            name='GearRequirements',
        ),
        migrations.DeleteModel(
            name='Notions',
        ),
    ]
