# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-24 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_enrollingrequirements_gearrequirements_notions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='totalParticipants',
        ),
    ]
