# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollingRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirementsForEnrolling', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GearRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredGear', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notionDiscussed', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='id',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='name',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='price',
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('description', models.TextField()),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodOfTime', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('scopeOfCourse', models.CharField(max_length=200)),
                ('participants', models.CharField(max_length=20)),
                ('totalParticipants', models.IntegerField(default=0)),
                ('video_url', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=100)),
            ],
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Courses'),
        ),
        migrations.AddField(
            model_name='gearrequirements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Courses'),
        ),
        migrations.AddField(
            model_name='enrollingrequirements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Courses'),
        ),
    ]
