# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200226_2221'),
    ]

    operations = [
    ]
